### ISSUE TITLE
重要的故事背景

### ISSUE THREAD

**Issue by lsongdev** [song940/the-programmer#3]
主角进入办公室后开始紧张地解决问题，最后终于搞定。

抬头一看时间已经到了凌晨，瞬间睡意来袭，主角趴在桌子上睡着。

当主角再次醒来时，天已经亮了，光线非常刺眼（这里暗示观众可能是幻觉）。

房间已经被紧紧锁住，无法出去。唯一了解外界的途径只有网络。

**Comment by gynsolomon** [comment]
哈哈，看上去好有趣的样子
